name: Weekly AI News Digest

on:
  schedule:
    # ML Monday - 8:00 AM UTC every Monday
    - cron: '0 8 * * 1'
    # Business Briefing - 8:00 AM UTC every Wednesday
    - cron: '0 8 * * 3'
    # Ethics Friday - 8:00 AM UTC every Friday
    - cron: '0 8 * * 5'
  workflow_dispatch:  # Allows manual triggering
    inputs:
      day:
        description: 'Which day to run (monday, wednesday, friday, or test-all)'
        required: false
        default: 'today'

jobs:
  send-news-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run AI News Digest
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        LINKEDIN_ORGANIZATION_ID: ${{ secrets.LINKEDIN_ORGANIZATION_ID }}
      run: |
        if [ "${{ github.event.inputs.day }}" == "test-all" ]; then
          python main_scheduled.py test-all
        elif [ "${{ github.event.inputs.day }}" != "" ] && [ "${{ github.event.inputs.day }}" != "today" ]; then
          python main_scheduled.py ${{ github.event.inputs.day }}
        else
          python main_scheduled.py
        fi

